const { record } = require('./rec');
const { entries, VIEWERS } = require('./common');
record('short-bingo', async d => {
  const { page, sleep } = d;
  const intro = d.card('Playtech × CasinoDaddy', 'The Racaroon 2 Bingo', 'A 3×3 board of in-game challenges. Every line and the full board is a giveaway to chat.', 3000);
  await page.locator('[data-tab=special]').click(); await sleep(800);
  const c = await d.comp();
  await c.locator('.menu-card[data-mode=BINGO]').click(); await sleep(2000);
  const b = await d.bingo();
  await b.waitForSelector('#cell0 textarea');
  await b.evaluate(() => { S.cells.forEach((x, i) => { if (i !== 4) x.d = false; }); S.cells[3].d = true; S.cells[0].d = true; S.lines = Object.keys(LINES).filter(lineDone); S.fx = null; S.winners = {}; save(); renderAll(); });
  await intro;

  await d.stream(true, 300, true);
  await d.cap('On stream: the challenges and the prize pool', 3000);
  await d.stream(false, 300);
  await d.cap('A challenge happens in the game: <b>Mark done</b>');
  await d.click(b.locator('#cell5 button'), { after: 200, fast: true });
  await d.stream(true, 300, true);
  await d.cap('<b>LINE!</b> The line\'s prize goes to chat', 3500);
  await d.cap('Entries open by themselves: chat types the keyword', 1500);
  await d.ff(true, 4);
  await d.chat(b, entries('Racaroon', 20), 200);
  await b.evaluate(() => testEntries());
  await sleep(1500);
  await d.cap('');
  await b.evaluate(() => draw());
  await sleep(800);
  await d.stream(true, 2200, false);
  await d.ff(false);
  await d.cap('The draw: names climb the game\'s jackpot bars', 3000);
  await d.cap('');
  await d.ff(true, 4);
  await b.waitForFunction(() => S.rf.spin && netNow() >= spinEnd(S.rf.spin), null, { timeout: 60000, polling: 200 });
  await d.ff(false);
  const w = await b.evaluate(() => { const e = winnerOf(S.rf.spin); return { pf: e.platform, user: e.user, name: e.name }; });
  await sleep(1500);
  await d.chat(b, [[w.pf, w.name, 'here!! 🦝', w.user]], 200);
  console.log('claimed?', await b.evaluate(() => S.rf.spin && S.rf.spin.claimed));
  await d.cap(`The winner turns <b>GRAND</b>: ${w.name} claims in chat`, 2400);
  await d.cap('');
  await d.card('Playtech × CasinoDaddy', 'The Racaroon 2 Bingo', '8 lines + full board · Live on Twitch, Kick and YouTube at once', 2500);
}, { bg: '/bingo/rr2/bg.webp' });
